name: Auto-merge Codex PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'BimBeau'
    steps:
      - uses: "peter-evans/enable-pull-request-automerge@v3"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: "squash"
      - name: Merge pull request
        run: gh pr merge ${{ github.event.pull_request.number }} --squash --admin --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
