name: Auto-merge Codex PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'BimBeau' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable auto-merge for PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GH_PAT_AUTOMERGE }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      - name: Merge PR with CLI
        run: gh pr merge ${{ github.event.pull_request.number }} --squash --admin --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_AUTOMERGE }}
